################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/low_power_manager.c \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/queue.c \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/systime.c \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/timeServer.c \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/trace.c \
C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/utilities.c 

OBJS += \
./Middlewares/LoRaWAN/Utilities/low_power_manager.o \
./Middlewares/LoRaWAN/Utilities/queue.o \
./Middlewares/LoRaWAN/Utilities/systime.o \
./Middlewares/LoRaWAN/Utilities/timeServer.o \
./Middlewares/LoRaWAN/Utilities/trace.o \
./Middlewares/LoRaWAN/Utilities/utilities.o 

C_DEPS += \
./Middlewares/LoRaWAN/Utilities/low_power_manager.d \
./Middlewares/LoRaWAN/Utilities/queue.d \
./Middlewares/LoRaWAN/Utilities/systime.d \
./Middlewares/LoRaWAN/Utilities/timeServer.d \
./Middlewares/LoRaWAN/Utilities/trace.d \
./Middlewares/LoRaWAN/Utilities/utilities.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/LoRaWAN/Utilities/low_power_manager.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/low_power_manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/low_power_manager.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Utilities/queue.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/queue.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Utilities/systime.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/systime.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/systime.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Utilities/timeServer.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/timeServer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/timeServer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Utilities/trace.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/trace.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/trace.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Utilities/utilities.o: C:/Users/Giulia\ Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities/utilities.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_FULL_LL_DRIVER -DNO_MAC_PRINTF -DREGION_EU868 -DREGION_AS923 -DREGION_AU915 -DREGION_CN470 -DREGION_CN779 -DREGION_EU433 -DREGION_KR920 -DREGION_IN865 -DREGION_US915 -DREGION_RU864 -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/Core/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Projects/B-L072Z-LRWAN1/Applications/LoRa/AT_Slave/LoRaWAN/App/inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/CMWX1ZZABZ-0xx" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/CMSIS/Include" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Middlewares/Third_Party/LoRaWAN/Patterns/Basic" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/Common" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/hts221" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/Components/sx1276" -I"C:/Users/Giulia Cioffi/Documents/Arduino/hardware/arduino_git/loraST/Drivers/BSP/B-L072Z-LRWAN1"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/LoRaWAN/Utilities/utilities.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


